services:
  db:
    image: postgres:alpine3.23
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: mdp
      POSTGRES_USER: marie
      POSTGRES_DB: guestbook

  adminer:
    image: adminer
    restart: always
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      - db